chain:
  # The chain id of the chain that the verifier program interacts with
  chain_id: 5611
  # The chain name of the chain that the verifier program interacts with
  chain_name: "opBNB"
  # The rpc url of the blockchain node which verifier program interacts with
  rpc_url: "https://opbnb-testnet.nodereal.io/v1/9e210feafbec4ed9bd48f855c2bd979a"
  # The block height at which verifier starts synchronizing data
  start_block: 26623154
  # block height interval for synchronizing data at one time
  offset_block: 1
contract:
  # The contract address of carv on this chain
  addr: "0x39afd848cd4a83cddd06f340ae584c547e53873d"
  # The contract address of tee on this chain
  tee_addr : "0x19baa72643aa11b28cb6251fd7596201778ead9a"
  # The topic id of the event corresponding to the attestation published by tee
  topic: "0x99a038e9d345d0b12130b3b1fb003bf8f2d3a5c27ce2a800bbb1608efff6c591"
wallet:
  # wallet mode, by which way to pass the private key
  # 0: through startup parameters
  # 1: through plain text private key in config file
  # 2: through path and password of the keystore in config file
  mode: 0
  # plain text private key, needed when mode is 1
  private_key: "cfe306ade442cde406f43cb9860ef851f11a510bb55f11853d1b693e74b0bd0b"
  # path of the keystore, needed when mode is 2
  keystore_path: "/Users/alice/.keystore"
  # password of the keystore, needed when mode is 2
  keystore_password: "123456"
